### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by monje** [dmatveev/pandoc-yaml-vars#3] opened 2016-03-14 04:29 UTC
Hi @dmatveev,

I'm having a build issue with the project. This is my process:
1. Git clone the repo.
2. create cabal sandbox
3. cabal update
4. cabal instal pandoc-yaml-vars

This is the output I get:

```
Building pandoc-yaml-vars-0.0.0.1...
Failed to install pandoc-yaml-vars-0.0.0.1
Build log ( ./pandoc-yaml-vars/.cabal-sandbox/logs/pandoc-yaml-vars-0.0.0.1.log ):
Configuring pandoc-yaml-vars-0.0.0.1...
Building pandoc-yaml-vars-0.0.0.1...
Preprocessing executable 'pandoc-yaml-vars' for pandoc-yaml-vars-0.0.0.1...
[1 of 2] Compiling Text.YamlVars.Processor ( Text/YamlVars/Processor.hs, dist/dist-sandbox-355eb38e/build/pandoc-yaml-vars/pandoc-yaml-vars-tmp/Text/YamlVars/Processor.o )
[2 of 2] Compiling Main             ( Main.hs, dist/dist-sandbox-355eb38e/build/pandoc-yaml-vars/pandoc-yaml-vars-tmp/Main.o )

Main.hs:24:4:
    Constructor ‘Link’ should have 3 arguments, but has been given 2
    In the pattern: Link ii (u, t)
    In a case alternative:
        (Link ii (u, t)) -> Link (p' ii) (process u d, process t d)
    In the expression:
      case i of {
        (Str s) -> Str (process s d)
        (Code a s) -> Code a (process s d)
        (Math m s) -> Math m (process s d)
        (RawInline f s) -> RawInline f (process s d)
        (Link ii (u, t)) -> Link (p' ii) (process u d, process t d)
        (Image ii (u, t)) -> Image (p' ii) (process u d, process t d)
        otherwise -> i }

Main.hs:27:13:
    No instance for (Walkable Inline b0) arising from a use of ‘walk’
    The type variable ‘b0’ is ambiguous
    Relevant bindings include p' :: b0 -> b0 (bound at Main.hs:27:8)
    Note: there are several potential instances:
      instance (Foldable t, Traversable t, Walkable a b) =>
               Walkable a (t b)
        -- Defined in ‘Text.Pandoc.Walk’
      instance [overlapping] (Walkable a b, Walkable a c) =>
                             Walkable a (b, c)
        -- Defined in ‘Text.Pandoc.Walk’
      instance Walkable Inline Block -- Defined in ‘Text.Pandoc.Walk’
      ...plus five others
    In the expression: walk (substInl d)
    In an equation for ‘p'’: p' = walk (substInl d)
    In an equation for ‘substInl’:
        substInl d i
          = case i of {
              (Str s) -> Str (process s d)
              (Code a s) -> Code a (process s d)
              (Math m s) -> Math m (process s d)
              (RawInline f s) -> RawInline f (process s d)
              (Link ii (u, t)) -> Link (p' ii) (process u d, process t d)
              (Image ii (u, t)) -> Image (p' ii) (process u d, process t d)
              otherwise -> i }
          where
              p' = walk (substInl d)
cabal: Error: some packages failed to install:
pandoc-yaml-vars-0.0.0.1 failed during the building phase. The exception was:
ExitFailure 1
```

Have you experienced this?

Is this similar to your build process?

**Comment by dmatveev** [comment] 2016-03-14 08:51
Hi Shawn,

I think it could be caused by pandoc version changes. Which one is installed on the machine?

In `.cabal` file, we have

```
                 , pandoc >= 1.15
                 , pandoc-types >= 1.12
```

Which puts requirements only on minimal version of pandoc, though new versions could break API and cause these issues.

**Comment by monje** [comment] 2016-03-14 23:31
Hi Dmitry,

I am using the latest LTS Haskell from Stackage ([LTS Haskell 5.8](https://www.stackage.org/lts-5.8))

The [`cabal.config`](https://www.stackage.org/lts/cabal.config) defines:

```
pandoc ==1.16.0.2,
pandoc-citeproc ==0.9,
pandoc-types ==1.16.1,
```

Version 1.16.0 introduced a lot of changes and after having a look, the following [change](https://raw.githubusercontent.com/jgm/pandoc/master/changelog) might be the cause of the issue.

```
pandoc (1.16)

  * Added `Attr` field to `Link` and `Image` (Mauro Bieg, #261, API change).

    + Added syntax for link and image attributes to pandoc's Markdown.
    + Updated readers and writers to use link and image attributes
      when appropriate.
    + Support image attributes in Docx, Textile, RST readers.
```

**Comment by dmatveev** [comment] 2016-03-15 09:41
Hi Shawn,

Yes this is likely an API breaker. So do you ship _this_ pandoc version everywhere so I can do a version bump, or we need to support both?

**Comment by monje** [comment] 2016-03-15 10:22
Hi Dmitry,

I'm happy to _only_ support the latest version (`1.16.0.2`) of pandoc. I generally build my toolset using LTS Haskell. That generally gives me a good selection of recent features without too many breaking changes.

Thanks!

**Comment by dmatveev** [comment] 2016-03-15 11:35
Ok, so I will update my environment and bump minimum supported version to 1.16.x.

**Comment by monje** [comment] 2016-03-15 11:55
Thank you very much, Dmitry!

**Comment by dmatveev** [comment] 2016-03-15 22:58
Fixed in 5750ed5817b7fb0435334c60281f169bde2ea7f7

**Comment by dmatveev** [comment] 2016-03-15 22:58
Shawn, by default I left all element attributes unmodified (no substitutions made there). Let me know if you have use case for that so I will extend it.

**Closed as completed by dmatveev** 2016-03-15 22:58 UTC

**Comment by monje** [comment] 2016-03-16 05:11
Brilliant. Very much appreciated, Dmitry.

Thanks again.
